# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Fighter', 'The Fighter Class'), ('Magician', 'The Magician Class'), ('Ranger', 'The Ranger Class')], max_length=150)),
                ('health', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('defence', models.IntegerField()),
                ('range_attack', models.IntegerField()),
                ('range_defence', models.IntegerField()),
                ('magic_attack', models.IntegerField()),
                ('magic_defence', models.IntegerField()),
                ('fight_description', models.CharField(max_length=750)),
                ('drop_experience_minimum', models.SmallIntegerField()),
                ('drop_experience_maximum', models.SmallIntegerField()),
                ('drop_gold_minimum', models.SmallIntegerField()),
                ('drop_gold_maximum', models.SmallIntegerField()),
                ('drop_item_rate', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
