# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatureGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('fighting_position', models.CharField(choices=[('FRONT', 'Creature is fighting from the front position'), ('BACK', 'Creature is fighting from the rear position')], max_length=5)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creature.Creature')),
            ],
            options={
                'db_table': 'creature_group',
            },
        ),
    ]
