# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:23
from __future__ import unicode_literals

import character.characters.characters
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_class', models.IntegerField(choices=[(1, character.characters.characters.Paladin), (2, character.characters.characters.Barbarian)])),
                ('name', models.CharField(max_length=150)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dexterity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('constitution', models.DecimalField(decimal_places=2, max_digits=19)),
                ('intelligence', models.DecimalField(decimal_places=2, max_digits=19)),
                ('wisdom', models.DecimalField(decimal_places=2, max_digits=19)),
                ('charisma', models.DecimalField(decimal_places=2, max_digits=19)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.DecimalField(decimal_places=2, max_digits=22)),
                ('max_health', models.IntegerField()),
                ('remaining_health', models.IntegerField()),
                ('points_to_allocate', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterMana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_mana', models.PositiveSmallIntegerField(default=50)),
                ('remaining_mana', models.PositiveSmallIntegerField(default=50)),
                ('max_pvp_mana', models.PositiveSmallIntegerField(default=10)),
                ('remaining_pvp_mana', models.PositiveSmallIntegerField(default=10)),
                ('mana_reloads', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'character_character_mana',
            },
        ),
        migrations.CreateModel(
            name='CharacterStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacks_made', models.IntegerField(default=0)),
                ('attacks_won', models.IntegerField(default=0)),
                ('harvests_made', models.IntegerField(default=0)),
                ('prayers_made', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'character_statistic',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='character_mana',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.CharacterMana'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_statistic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.CharacterStatistic'),
        ),
        migrations.AddField(
            model_name='character',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
